/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiPortalWebhookRouteImport } from './routes/api.portal.webhook'
import { Route as RoomRoomIdRoleRouteImport } from './routes/room.$roomId.$role'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalWebhookRoute = ApiPortalWebhookRouteImport.update({
  id: '/api/portal/webhook',
  path: '/api/portal/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoleRoute = RoomRoomIdRoleRouteImport.update({
  id: '/room/$roomId/$role',
  path: '/room/$roomId/$role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/portal/webhook': typeof ApiPortalWebhookRoute
  '/room/$roomId/$role': typeof RoomRoomIdRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/portal/webhook': typeof ApiPortalWebhookRoute
  '/room/$roomId/$role': typeof RoomRoomIdRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/portal/webhook': typeof ApiPortalWebhookRoute
  '/room/$roomId/$role': typeof RoomRoomIdRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/health' | '/api/portal/webhook' | '/room/$roomId/$role'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/health' | '/api/portal/webhook' | '/room/$roomId/$role'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/portal/webhook'
    | '/room/$roomId/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPortalWebhookRoute: typeof ApiPortalWebhookRoute
  RoomRoomIdRoleRoute: typeof RoomRoomIdRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/webhook': {
      id: '/api/portal/webhook'
      path: '/api/portal/webhook'
      fullPath: '/api/portal/webhook'
      preLoaderRoute: typeof ApiPortalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/$role': {
      id: '/room/$roomId/$role'
      path: '/room/$roomId/$role'
      fullPath: '/room/$roomId/$role'
      preLoaderRoute: typeof RoomRoomIdRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPortalWebhookRoute: ApiPortalWebhookRoute,
  RoomRoomIdRoleRoute: RoomRoomIdRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
